# Server Configuration
server.port=8081

# Logging Configuration
logging.level.org.atmosphere=warn

# Vaadin Configuration
vaadin.launch-browser=true
vaadin.whitelisted-packages=com.vaadin,org.vaadin,dev.hilla,com.example.application

# JPA Configuration
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=urcbudgetapp@gmail.com
spring.mail.password=ethftdnshnuisvjc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# DataSource Configuration - BGTOOLS
spring.datasource.bgtool.url=jdbc:sqlserver://localhost:1433;databaseName=BGTOOLS;encrypt=true;trustServerCertificate=true;
spring.datasource.bgtool.username=sa
spring.datasource.bgtool.password=1234
spring.datasource.bgtool.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# DataSource Configuration - LiveData
spring.datasource.livedata.url=jdbc:sqlserver://localhost:1433;databaseName=LiveData;encrypt=true;trustServerCertificate=true;
spring.datasource.livedata.username=sa
spring.datasource.livedata.password=1234
spring.datasource.livedata.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# DataSource Configuration - OldBGTOOLS
spring.datasource.oldbgtool.url=jdbc:sqlserver://localhost:1433;databaseName=URCDBTASK;encrypt=true;trustServerCertificate=true;
spring.datasource.oldbgtool.username=sa
spring.datasource.oldbgtool.password=1234
spring.datasource.oldbgtool.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver


